// --- ESTILOS ---
export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    backgroundColor: '#ecfeff',
    fontFamily: 'Arial, sans-serif',
    padding: '20px',
  },
  card: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '16px',
    boxShadow: '0 4px 20px rgba(6, 182, 212, 0.1)',
    textAlign: 'center',
    maxWidth: '400px',
    width: '100%',
  },
  title: {
    color: '#06b6d4',
    marginBottom: '1.5rem',
    fontSize: '2rem',
    fontWeight: 'bold',
  },
  input: {
    width: '100%',
    padding: '12px',
    margin: '8px 0',
    borderRadius: '8px',
    border: '1px solid #cbd5e1',
    boxSizing: 'border-box',
    fontSize: '1rem',
  },
  button: {
    backgroundColor: '#06b6d4',
    color: 'white',
    border: 'none',
    padding: '12px',
    borderRadius: '8px',
    fontSize: '1rem',
    fontWeight: 'bold',
    cursor: 'pointer',
    width: '100%',
    marginTop: '10px',
  },
  buttonSecondary: {
    backgroundColor: 'white',
    color: '#06b6d4',
    border: '2px solid #06b6d4',
    marginTop: '10px',
  },
  link: {
    color: '#0891b2',
    textDecoration: 'underline',
    cursor: 'pointer',
    fontSize: '0.9rem',
    marginTop: '15px',
    display: 'block',
  },
  tripListContainer: {
    width: '100%',
    maxWidth: '600px',
    marginTop: '20px',
  },
  tripCard: {
    backgroundColor: 'white',
    padding: '1.5rem',
    borderRadius: '12px',
    marginBottom: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.05)',
    textAlign: 'left',
    borderLeft: '5px solid #06b6d4',
  },
  tripHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '10px',
  },
  tripPrice: {
    fontSize: '1.2rem',
    fontWeight: 'bold',
    color: '#0e7490',
  },
  tripRoute: {
    fontSize: '1.1rem',
    fontWeight: 'bold',
    color: '#334155',
    marginBottom: '5px',
  },
  tripDetails: {
    fontSize: '0.9rem',
    color: '#64748b',
  },
  requestButton: {
    backgroundColor: '#0e7490',
    color: 'white',
    border: 'none',
    padding: '8px 16px',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    marginTop: '10px',
    width: '100%',
  },
};
